apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-config
  namespace: iot-app
data:
  # ── Kafka ──
  KAFKA_BOOTSTRAP: "kafka-0.kafka-headless.iot-infra.svc.cluster.local:9092,kafka-1.kafka-headless.iot-infra.svc.cluster.local:9092,kafka-2.kafka-headless.iot-infra.svc.cluster.local:9092"

  # ── PostgreSQL ──
  POSTGRES_HOST: "postgres.iot-infra.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "iot_platform"
  POSTGRES_USER: "iot_user"

  # ── MongoDB ──
  MongoDB_URL: "http://MongoDB.iot-infra.svc.cluster.local:8086"
  MongoDB_ORG: "iot"
  MongoDB_BUCKET: "telemetry"

  # ── MongoDB ──
  MONGODB_URI: "mongodb://mongodb.iot-infra.svc.cluster.local:27017/iot_platform"

  # ── Broker ──
  BROKER_PORT: "1883"
  BROKER_INTERNAL_API: "http://iot-backend.iot-app.svc.cluster.local:8000/internal/verify-credentials"

  # ── Application ──
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-config
  namespace: iot-broker
data:
  KAFKA_BOOTSTRAP: "kafka-0.kafka-headless.iot-infra.svc.cluster.local:9092,kafka-1.kafka-headless.iot-infra.svc.cluster.local:9092,kafka-2.kafka-headless.iot-infra.svc.cluster.local:9092"
  POSTGRES_HOST: "postgres.iot-infra.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "iot_platform"
  POSTGRES_USER: "iot_user"
  MongoDB_URL: "http://MongoDB.iot-infra.svc.cluster.local:8086"
  MongoDB_ORG: "iot"
  MongoDB_BUCKET: "telemetry"
  MONGODB_URI: "mongodb://mongodb.iot-infra.svc.cluster.local:27017/iot_platform"
  BROKER_PORT: "1883"
  BROKER_INTERNAL_API: "http://iot-backend.iot-app.svc.cluster.local:8000/internal/verify-credentials"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
