apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
  namespace: iot-infra
  labels:
    app: influxdb
spec:
  serviceName: influxdb-headless
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:2.7-alpine
          ports:
            - containerPort: 8086
              name: http
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: "setup"
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: "admin"
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              value: "influxdb-password"
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: "iot"
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: "telemetry"
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: iot-secrets
                  key: INFLUXDB_ADMIN_TOKEN
          volumeMounts:
            - name: influxdb-data
              mountPath: /var/lib/influxdb2
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 8086
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8086
            initialDelaySeconds: 5
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: influxdb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
